# -*- coding: utf-8 -*-
"""PCTC_SampleR1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AyUUGaJeJ4CVf0LNbImBqmePYf5do1Po

# PCTC Sample Round 0
"""

#Q1
num1 = int(input("Number1(0 to 1000)"))
num2 = int(input("number2( o to 1000)"))

if num1>num2:
  x=num1-num2
else:
  x=num2-num1
print(x)

#Q2
word = input("key in a word ")
word = word * 4
if len(word) > 30:
   print(word)
else:
   n = 30-len(word)
   #print(n)
   #print(word)
   for i in range(n):
     word= word + word[i]
   print(word)

'abc' * 4

#Q3
num = int(input("What is the number:"))
if num > 50:
  print("yes,dream big.")
else:
  print("on the small side")

#Q4
result = ""
firstnum = int(input("Num 1 "))
oper = input("input an operator")
secnum = int(input("Num 2 "))
if oper == "*":
  result = firstnum * secnum
elif oper == "+":
  result = firstnum + secnum
else:
  print("Operator should be addition or multiplication")
print(result)

#Q5
greeting = input("Say a greeting.")
name = input("what is your name?")
print(greeting," ",name)

#Q6
name1 = input()
name2 = input()
name3 = input()
name4 = input()
name5 = input()
namelist = [name1,name2,name3,name4,name5]
Order = ["1st","2nd","3rd","4th","5th"]
for i in range(5):
 # print(namelist[i])
  if namelist[i]=="Ellie":
    print(i+1)
#print(namelist.index("Ellie"))
print(Order[namelist.index("Ellie")])

#Q7
a=input()
b=input()
print(a+b) #QW without space between
print(a,b) #Q W with space between

#Q8
a=int(input())
print("\./")
for i in range(a):
  print(".|.")

#Q9

dance_steps=["<","+","&",">"]
dance_routine="<+&>"
#dance_steps=dance_steps*4
dance_routine=dance_routine*4
#print(dance_routine[0:16])
startstep=input(":")
for i in range(4):
  if dance_steps[i]==startstep:
 #   for j in range(8):
 #     print(dance_steps[i+j])
    print(dance_routine[i:i+8])
    break

#Q10
I=0 #2
M=0 #1
C=0 #3
W=0 #1

icecream=input()
if len(icecream)!=6:
  print("Key in 6 chars.")
else:
  I=icecream.count("I")
  M=icecream.count("M")
  C=icecream.count("C")
  W=icecream.count("W")
  #print(":",M,W,I,C) #1,1,2,3
  for i in range(1-M):
    print("M")
  for i in range(1-W):
    print("W")
  for i in range(2-I):
    print("I")
  for i in range(3-C):
    print ("C")

